/**
 * Error
 */


exports.NO_CONNECTION_ERROR = -1;
exports.ERROR_JSON_OBJECT = 1;

exports.ERROR_PARAM_INVALID = 100;
exports.ERROR_EMAIL_NOT_EXIST = 102;
exports.ERROR_PARAM_PASSWORD_INVALID = 103;
exports.ERROR_WALLET_INVALID = 104;
exports.ERROR_NOT_GEN_SHARE_CODE = 105;
exports.ERROR_DATA_INVALID = 106;
exports.ERROR_NOT_SHARE_MYSELF = 107;
exports.ERROR_WALLET_NOT_EXIST = 108;
exports.ERROR_SHARE_CODE_INVALID = 109;
exports.ERROR_SET_PERMISSION_FAIL = 110;

exports.ERROR_EMAIL_EXISTS = 200;
exports.ERROR_SERIALS = 201;
exports.ERROR_WARNING_INFO = 202;
exports.ERROR_EVENT_EXPIRE = 203;
exports.ERROR_SERVER = 204;
exports.ERROR_LOGIN_FAIL = 205;
exports.ERROR_EMAIL_INVALID = 206;
exports.ERROR_EMAIL_OR_PASSWORD_WRONG = 207;
exports.ERROR_USER_ID_NULL = 209;
exports.ERROR_SECRET_FAIL = 210;
exports.ERROR_LIMIT_DEVICE = 212;
exports.ERROR_USER_NOT_LOGIN = 213;
exports.ERROR_INVITE_DATA = 214;
exports.ERROR_REMOVE_DEVICE = 215;
exports.ERROR_SOCIAL_ID_NOT_FOUND = 216;

exports.ERROR_BIG_DATA = 401;
exports.ERROR_SERVER_MAINTENANCE = 404;
exports.ERROR_OLD_VERSION = 406;

exports.ERROR_TIMEOUT = 502;

exports.ERROR_DATA_INVALID_FORMAT = 701;
exports.ERROR_WALLET_CAN_NOT_READ = 702;
exports.ERROR_WALLET_CAN_NOT_WRITE = 703;
exports.ERROR_INFO = 704;
exports.ERROR_NOT_DEL_WALLET_SHARED = 705;
exports.ERROR_AUTHENTICATE_EXPIRE = 706;
exports.ERROR_FLAG = 707; //cờ add nhưng đã tồn tại
exports.ERROR_DATE_TIME = 708; //Loi dinh dang ngay thang sai
exports.ERROR_FLAG_EDIT = 709; //cờ edit nhưng ko tồn tại trên sv

exports.ERROR_USER_NOT_EXIT = 901;
exports.ERROR_USER_HAVE_NOT_PERMISSION = 902;
exports.ERROR_USER_UNAUTHORIZED = 903;
exports.ERROR_SOCIAL_ID_AND_EMAIL_REGISTERED = 908;
exports.ERROR_SOCIAL_ID_REGISTERED_WITH_ANOTHER_EMAIL = 909;
exports.ERROR_SOCIAL_EMAIL_REGISTERED_WITHOUT_SOCIAL_ID = 910;
exports.ERROR_SOCIAL_EMAIL_REGISTERED_WITH_ANOTHER_SOCIAL_ID = 911;